version: "2.1"

networks:
  ledger:
    driver: bridge

services:
  mongo:
    container_name: ledger-mongo
    image: mongo:latest
    ports:
      - "3010:27017"
    networks:
      - ledger
  redis:
    container_name: ledger-redis
    image: redis:latest
    networks:
      - ledger
  eyeshade-worker:
    container_name: eyeshade-worker
    command: "npm run eyeshade-worker"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "MONGODB_URI=mongodb://mongo/eyeshade"
      - "SERVICE=eyeshade"
    depends_on:
      - mongo
      - redis
    networks:
      - ledger
  eyeshade-web:
    container_name: eyeshade-web
    ports:
      - "3002:3002"
    command: "npm run eyeshade-server"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "MONGODB_URI=mongodb://mongo/eyeshade"
      - "SERVICE=eyeshade"
    depends_on:
      - mongo
      - redis
    networks:
      - ledger
  ledger-worker:
    container_name: ledger-worker
    command: "npm run ledger-worker"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "SERVICE=ledger"
    depends_on:
      - mongo
      - redis
    networks:
      - ledger
  ledger-web:
    container_name: ledger-web
    ports:
      - "3001:3001"
    command: "npm run ledger-server"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "SERVICE=ledger"
      - PUBLISHERS_TAKEOVER
    depends_on:
      - mongo
      - redis
    networks:
      - ledger
  balance-web:
    container_name: balance-web
    ports:
      - "3003:3003"
    command: "npm run balance-server"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "SERVICE=balance"
    depends_on:
      - redis
    networks:
      - ledger
  helper-worker:
    container_name: helper-worker
    command: "npm run helper-worker"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "MONGODB_URI=mongodb://mongo/helper"
      - "SERVICE=helper"
    depends_on:
      - mongo
      - redis
    networks:
      - ledger
  helper-web:
    container_name: helper-web
    ports:
      - "3004:3004"
    command: "npm run helper-server"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "MONGODB_URI=mongodb://mongo/helper"
      - "SERVICE=helper"
    depends_on:
      - mongo
      - redis
    networks:
      - ledger
  grant-redis:
    container_name: grant-redis
    image: redis:latest
    networks:
      - ledger
  grant-web:
    container_name: grant-web
    image: brave/bat-go:latest
    ports:
      - "3333:3333"
    environment:
      - "REDIS_URL=${REDIS_URL-redis://grant-redis:6379}"
      - BAT_SETTLEMENT_ADDRESS
      - GRANT_SIGNATOR_PUBLIC_KEY
      - GRANT_WALLET_CARD_ID
      - GRANT_WALLET_PRIVATE_KEY
      - GRANT_WALLET_PUBLIC_KEY
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
    depends_on:
      - mongo
      - grant-redis
    networks:
      - ledger
  # publishers-web:
  #   container_name: publishers-web
  #   image: brave/publishers:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - ledger